// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Linq;

namespace DemoApp.ConsoleUI.Models
{
    /// <summary> Model factory for models. </summary>
    public static partial class DemoAppConsoleUIModelFactory
    {
        /// <summary> Initializes a new instance of <see cref="Models.RespLogin"/>. </summary>
        /// <param name="error"></param>
        /// <param name="errorDescription"></param>
        /// <param name="token"></param>
        /// <returns> A new <see cref="Models.RespLogin"/> instance for mocking. </returns>
        public static RespLogin RespLogin(ErrorCodeEnum? error = null, string errorDescription = null, string token = null)
        {
            return new RespLogin(error, errorDescription, token);
        }

        /// <summary> Initializes a new instance of <see cref="Models.AccountItemResponseList"/>. </summary>
        /// <param name="error"></param>
        /// <param name="errorDescription"></param>
        /// <param name="items"></param>
        /// <returns> A new <see cref="Models.AccountItemResponseList"/> instance for mocking. </returns>
        public static AccountItemResponseList AccountItemResponseList(ErrorCodeEnum? error = null, string errorDescription = null, IEnumerable<AccountItem> items = null)
        {
            items ??= new List<AccountItem>();

            return new AccountItemResponseList(error, errorDescription, items?.ToList());
        }

        /// <summary> Initializes a new instance of <see cref="Models.AccountItem"/>. </summary>
        /// <param name="login"></param>
        /// <param name="email"></param>
        /// <returns> A new <see cref="Models.AccountItem"/> instance for mocking. </returns>
        public static AccountItem AccountItem(string login = null, string email = null)
        {
            return new AccountItem(login, email);
        }

        /// <summary> Initializes a new instance of <see cref="Models.RespRegistration"/>. </summary>
        /// <param name="error"></param>
        /// <param name="errorDescription"></param>
        /// <param name="id"></param>
        /// <returns> A new <see cref="Models.RespRegistration"/> instance for mocking. </returns>
        public static RespRegistration RespRegistration(ErrorCodeEnum? error = null, string errorDescription = null, int? id = null)
        {
            return new RespRegistration(error, errorDescription, id);
        }
    }
}
