// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace DemoApp.ConsoleUI.Models
{
    /// <summary> The AccountItemResponseList. </summary>
    public partial class AccountItemResponseList
    {
        /// <summary> Initializes a new instance of <see cref="AccountItemResponseList"/>. </summary>
        internal AccountItemResponseList()
        {
            Items = new ChangeTrackingList<AccountItem>();
        }

        /// <summary> Initializes a new instance of <see cref="AccountItemResponseList"/>. </summary>
        /// <param name="error"></param>
        /// <param name="errorDescription"></param>
        /// <param name="items"></param>
        internal AccountItemResponseList(ErrorCodeEnum? error, string errorDescription, IReadOnlyList<AccountItem> items)
        {
            Error = error;
            ErrorDescription = errorDescription;
            Items = items;
        }

        /// <summary> Gets the error. </summary>
        public ErrorCodeEnum? Error { get; }
        /// <summary> Gets the error description. </summary>
        public string ErrorDescription { get; }
        /// <summary> Gets the items. </summary>
        public IReadOnlyList<AccountItem> Items { get; }
    }
}
