// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure;

namespace DemoApp.ConsoleUI.Models
{
    public partial class AccountItemResponseList
    {
        internal static AccountItemResponseList DeserializeAccountItemResponseList(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            ErrorCodeEnum? error = default;
            string errorDescription = default;
            IReadOnlyList<AccountItem> items = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("error"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    error = new ErrorCodeEnum(property.Value.GetInt32());
                    continue;
                }
                if (property.NameEquals("errorDescription"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        errorDescription = null;
                        continue;
                    }
                    errorDescription = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("items"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    List<AccountItem> array = new List<AccountItem>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(AccountItem.DeserializeAccountItem(item));
                    }
                    items = array;
                    continue;
                }
            }
            return new AccountItemResponseList(error, errorDescription, items ?? new ChangeTrackingList<AccountItem>());
        }

        /// <summary> Deserializes the model from a raw response. </summary>
        /// <param name="response"> The response to deserialize the model from. </param>
        internal static AccountItemResponseList FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeAccountItemResponseList(document.RootElement);
        }
    }
}
