// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace DemoApp.ConsoleUI.Models
{
    /// <summary> The AccountItem. </summary>
    public partial class AccountItem
    {
        /// <summary> Initializes a new instance of <see cref="AccountItem"/>. </summary>
        internal AccountItem()
        {
        }

        /// <summary> Initializes a new instance of <see cref="AccountItem"/>. </summary>
        /// <param name="id"></param>
        /// <param name="login"></param>
        /// <param name="email"></param>
        internal AccountItem(int? id, string login, string email)
        {
            Id = id;
            Login = login;
            Email = email;
        }

        /// <summary> Gets the id. </summary>
        public int? Id { get; }
        /// <summary> Gets the login. </summary>
        public string Login { get; }
        /// <summary> Gets the email. </summary>
        public string Email { get; }
    }
}
