// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace DemoApp.ConsoleUI.Models
{
    /// <summary> The ReqLogin. </summary>
    public partial class ReqLogin
    {
        /// <summary> Initializes a new instance of <see cref="ReqLogin"/>. </summary>
        public ReqLogin()
        {
        }

        /// <summary> Initializes a new instance of <see cref="ReqLogin"/>. </summary>
        /// <param name="login"></param>
        /// <param name="password"></param>
        internal ReqLogin(string login, string password)
        {
            Login = login;
            Password = password;
        }

        /// <summary> Gets or sets the login. </summary>
        public string Login { get; set; }
        /// <summary> Gets or sets the password. </summary>
        public string Password { get; set; }
    }
}
