// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace DemoApp.ConsoleUI.Models
{
    public partial class ReqRegister : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Token))
            {
                if (Token != null)
                {
                    writer.WritePropertyName("token"u8);
                    writer.WriteStringValue(Token);
                }
                else
                {
                    writer.WriteNull("token");
                }
            }
            if (Optional.IsDefined(Login))
            {
                if (Login != null)
                {
                    writer.WritePropertyName("login"u8);
                    writer.WriteStringValue(Login);
                }
                else
                {
                    writer.WriteNull("login");
                }
            }
            if (Optional.IsDefined(Email))
            {
                if (Email != null)
                {
                    writer.WritePropertyName("email"u8);
                    writer.WriteStringValue(Email);
                }
                else
                {
                    writer.WriteNull("email");
                }
            }
            if (Optional.IsDefined(Password))
            {
                if (Password != null)
                {
                    writer.WritePropertyName("password"u8);
                    writer.WriteStringValue(Password);
                }
                else
                {
                    writer.WriteNull("password");
                }
            }
            writer.WriteEndObject();
        }

        /// <summary> Convert into a <see cref="RequestContent"/>. </summary>
        internal virtual RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }
    }
}
