// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace DemoApp.ConsoleUI.Models
{
    /// <summary> The ReqRegister. </summary>
    public partial class ReqRegister
    {
        /// <summary> Initializes a new instance of <see cref="ReqRegister"/>. </summary>
        public ReqRegister()
        {
        }

        /// <summary> Initializes a new instance of <see cref="ReqRegister"/>. </summary>
        /// <param name="token"></param>
        /// <param name="login"></param>
        /// <param name="email"></param>
        /// <param name="password"></param>
        internal ReqRegister(string token, string login, string email, string password)
        {
            Token = token;
            Login = login;
            Email = email;
            Password = password;
        }

        /// <summary> Gets or sets the token. </summary>
        public string Token { get; set; }
        /// <summary> Gets or sets the login. </summary>
        public string Login { get; set; }
        /// <summary> Gets or sets the email. </summary>
        public string Email { get; set; }
        /// <summary> Gets or sets the password. </summary>
        public string Password { get; set; }
    }
}
