// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace DemoApp.ConsoleUI.Models
{
    /// <summary> The RequestTokenBased. </summary>
    public partial class RequestTokenBased
    {
        /// <summary> Initializes a new instance of <see cref="RequestTokenBased"/>. </summary>
        public RequestTokenBased()
        {
        }

        /// <summary> Initializes a new instance of <see cref="RequestTokenBased"/>. </summary>
        /// <param name="token"></param>
        internal RequestTokenBased(string token)
        {
            Token = token;
        }

        /// <summary> Gets or sets the token. </summary>
        public string Token { get; set; }
    }
}
