// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;

namespace DemoApp.ConsoleUI.Models
{
    public partial class RespLogin
    {
        internal static RespLogin DeserializeRespLogin(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            ErrorCodeEnum? error = default;
            string errorDescription = default;
            string token = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("error"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    error = new ErrorCodeEnum(property.Value.GetInt32());
                    continue;
                }
                if (property.NameEquals("errorDescription"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        errorDescription = null;
                        continue;
                    }
                    errorDescription = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("token"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        token = null;
                        continue;
                    }
                    token = property.Value.GetString();
                    continue;
                }
            }
            return new RespLogin(error, errorDescription, token);
        }

        /// <summary> Deserializes the model from a raw response. </summary>
        /// <param name="response"> The response to deserialize the model from. </param>
        internal static RespLogin FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeRespLogin(document.RootElement);
        }
    }
}
